---
- hosts: all
  user: opc
  become: true

  #vars_files:
  #  - vars.yml

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

  tasks:
    - name: DNF update the system
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: install Nginx services
      ansible.builtin.dnf:
        name: "nginx"
        state: present


    #- name: Copy named configuraation files.
    #  copy:
    #    src: "{{ item.src }}"
    #    dest: "{{ item.dest }}"
    #    owner: root
    #    group: root
    #    mode: 0644
    #  with_items:
    #    - src: named/named.conf
    #      dest: /etc/named.conf
    #  notify:
    #    - restart named

    - name: Ensure nginx is start and configure to run at boot
      service:
        name: nginx
        state: started
        enabled: true
